export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING'
export const CLEAR_FORGOT_PASSWORD_STATE = 'CLEAR_FORGOT_PASSWORD_STATE'

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING'
export const CLEAR_RESET_PASSWORD_STATE = 'CLEAR_RESET_PASSWORD_STATE'

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE'

export const COUNTRYLIST_SUCCESS = 'COUNTRYLIST_SUCCESS'
export const COUNTRYLIST_FAIL = 'COUNTRYLIST_FAIL'
export const COUNTRYLIST_LOADING = 'COUNTRYLIST_LOADING'

export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS'
export const OTP_VERIFY_FAIL = 'OTP_VERIFY_FAIL'
export const OTP_VERIFY_LOADING = 'OTP_VERIFY_LOADING'

export const CHECK_REFERRER_SUCCESS = 'CHECK_REFERRER_SUCCESS'
export const CHECK_REFERRER_FAIL = 'CHECK_REFERRER_FAIL'
export const CHECK_REFERRER_LOADING = 'CHECK_REFERRER_LOADING'
export const CHECK_REFERRER_SKIP = 'CHECK_REFERRER_SKIP'

export const WELCOME_SUCCESS = 'WELCOME_SUCCESS'
export const WELCOME_PENDING = 'WELCOME_PENDING'

export const DASHBOARD_BANNER_SUCCESS = 'DASHBOARD_BANNER_SUCCESS'
export const DASHBOARD_BANNER_FAIL = 'DASHBOARD_BANNER_FAIL'
export const DASHBOARD_BANNER_LOADING = 'DASHBOARD_BANNER_LOADING'

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING'

export const PRODUCT_LIST_FILTER_SUCCESS = 'PRODUCT_LIST_FILTER_SUCCESS'
export const PRODUCT_LIST_FILTER_FAIL = 'PRODUCT_LIST_FILTER_FAIL'
export const PRODUCT_LIST_FILTER_LOADING = 'PRODUCT_LIST_FILTER_LOADING'

export const SERIAL_NUMBER_SUCCESS = 'SERIAL_NUMBER_SUCCESS'
export const SERIAL_NUMBER_FAIL = 'SERIAL_NUMBER_FAIL'
export const SERIAL_NUMBER_LOADING = 'SERIAL_NUMBER_LOADING'

export const WARRANTY_REGISTER_STEP_FIRST_SUCCESS = 'WARRANTY_REGISTER_STEP_FIRST_SUCCESS'
export const WARRANTY_REGISTER_STEP_FIRST_FAIL = 'WARRANTY_REGISTER_STEP_FIRST_FAIL'
export const WARRANTY_REGISTER_STEP_FIRST_LOADING = 'WARRANTY_REGISTER_STEP_FIRST_LOADING'
export const CLEAR_WARRANTY_REGISTER_STEP_FIRST = 'CLEAR_WARRANTY_REGISTER_STEP_FIRST'

export const WARRANTY_REGISTER_STEP_SECOND_SUCCESS = 'WARRANTY_REGISTER_STEP_SECOND_SUCCESS'
export const WARRANTY_REGISTER_STEP_SECOND_FAIL = 'WARRANTY_REGISTER_STEP_SECOND_FAIL'
export const WARRANTY_REGISTER_STEP_SECOND_LOADING = 'WARRANTY_REGISTER_STEP_SECOND_LOADING'

export const NEWSLIST_SUCCESS = 'NEWSLIST_SUCCESS'
export const NEWSLIST_FAIL = 'NEWSLIST_FAIL'
export const NEWSLIST_LOADING = 'NEWSLIST_LOADING'

export const CATEGORY_NEWS_SUCCESS = 'CATEGORY_NEWS_SUCCESS'
export const CATEGORY_NEWS_FAIL = 'CATEGORY_NEWS_FAIL'
export const CATEGORY_NEWS_LOADING = 'CATEGORY_NEWS_LOADING'

export const HALO_STORY_LIST_SUCCESS = 'HALO_STORY_LIST_SUCCESS'
export const HALO_STORY_LIST_FAIL = 'HALO_STORY_LIST_FAIL'
export const HALO_STORY_LIST_LOADING = 'HALO_STORY_LIST_LOADING'

export const HALO_STORY_DETAILS_SUCCESS = 'HALO_STORY_DETAILS_SUCCESS'
export const HALO_STORY_DETAILS_FAIL = 'HALO_STORY_DETAILS_FAIL'
export const HALO_STORY_DETAILS_LOADING = 'HALO_STORY_DETAILS_LOADING'

export const TERMS_AND_CONDITIONS_SUCCESS = 'TERMS_AND_CONDITIONS_SUCCESS'
export const TERMS_AND_CONDITIONS_FAIL = 'TERMS_AND_CONDITIONS_FAIL'
export const TERMS_AND_CONDITIONS_LOADING = 'TERMS_AND_CONDITIONS_LOADING'

export const SHOW_NAVIGATION = 'SHOW_NAVIGATION'
export const HIDE_NAVIGATION = 'HIDE_NAVIGATION'

export const MY_PRODUCT_LIST_SUCCESS = 'MY_PRODUCT_LIST_SUCCESS'
export const MY_PRODUCT_LIST_LOADING = 'MY_PRODUCT_LIST_LOADING'
export const MY_PRODUCT_LIST_FAIL = 'MY_PRODUCT_LIST_FAIL'

export const MY_PRODUCT_DETAILS_SUCCESS = 'MY_PRODUCT_DETAILS_SUCCESS'
export const MY_PRODUCT_DETAILS_LOADING = 'MY_PRODUCT_DETAILS_LOADING'
export const MY_PRODUCT_DETAILS_FAIL = 'MY_PRODUCT_DETAILS_FAIL'

export const E_REPAIR_SUCCESS = 'E_REPAIR_SUCCESS'
export const E_REPAIR_LOADING = 'E_REPAIR_LOADING'
export const E_REPAIR_FAIL = 'E_REPAIR_FAIL'

export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_LOADING = 'REVIEW_LIST_LOADING'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'

export const MY_PRODUCT_REVIEW_SUBMIT_SUCCESS = 'MY_PRODUCT_REVIEW_SUBMIT_SUCCESS'
export const MY_PRODUCT_REVIEW_SUBMIT_LOADING = 'MY_PRODUCT_REVIEW_SUBMIT_LOADING'
export const MY_PRODUCT_REVIEW_SUBMIT_FAIL = 'MY_PRODUCT_REVIEW_SUBMIT_FAIL'
export const CLEAR_MY_PRODUCT_REVIEW_STATE = 'CLEAR_MY_PRODUCT_REVIEW_STATE'

export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS'
export const NEWS_LIST_LOADING = 'NEWS_LIST_LOADING'
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL'
export const CLEAR_NEWS_LIST_STATE = 'CLEAR_NEWS_LIST_STATE'

export const NEWS_LIST_BY_CATEGORY_SUCCESS = 'NEWS_LIST_BY_CATEGORY_SUCCESS'
export const NEWS_LIST_BY_CATEGORY_LOADING = 'NEWS_LIST_BY_CATEGORY_LOADING'
export const NEWS_LIST_BY_CATEGORY_FAIL = 'NEWS_LIST_BY_CATEGORY_FAIL'
export const CLEAR_NEWS_LIST_BY_CATEGORY_STATE = 'CLEAR_NEWS_LIST_BY_CATEGORY_STATE'

export const NEWS_DETAIL_SUCCESS = 'NEWS_DETAIL_SUCCESS'
export const NEWS_DETAIL_LOADING = 'NEWS_DETAIL_LOADING'
export const NEWS_DETAIL_FAIL = 'NEWS_DETAIL_FAIL'
export const CLEAR_NEWS_DETAIL_STATE = 'CLEAR_NEWS_DETAIL_STATE'

export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS'
export const MY_PROFILE_LOADING = 'MY_PROFILE_LOADING'
export const MY_PROFILE_FAIL = 'MY_PROFILE_FAIL'

export const MY_PROFILE_UPDATE_SUCCESS = 'MY_PROFILE_UPDATE_SUCCESS'
export const MY_PROFILE_UPDATE_LOADING = 'MY_PROFILE_UPDATE_LOADING'
export const MY_PROFILE_UPDATE_FAIL = 'MY_PROFILE_UPDATE_FAIL'

export const MY_PROFILE_IMAGE_UPDATE_SUCCESS = 'MY_PROFILE_IMAGE_UPDATE_SUCCESS'
export const MY_PROFILE_IMAGE_UPDATE_LOADING = 'MY_PROFILE_IMAGE_UPDATE_LOADING'
export const MY_PROFILE_IMAGE_UPDATE_FAIL = 'MY_PROFILE_IMAGE_UPDATE_FAIL'
export const CLEAR_PROFILE_IMAGE_UPDATE = 'CLEAR_PROFILE_IMAGE_UPDATE'

export const MY_PROFILE_PASSWORD_UPDATE_SUCCESS = 'MY_PROFILE_PASSWORD_UPDATE_SUCCESS'
export const MY_PROFILE_PASSWORD_UPDATE_LOADING = 'MY_PROFILE_PASSWORD_UPDATE_LOADING'
export const MY_PROFILE_PASSWORD_UPDATE_FAIL = 'MY_PROFILE_PASSWORD_UPDATE_FAIL'

export const PRODUCT_CATALOG_DETAILS_SUCCESS = 'PRODUCT_CATALOG_DETAILS_SUCCESS'
export const PRODUCT_CATALOG_DETAILS_LOADING = 'PRODUCT_CATALOG_DETAILS_LOADING'
export const PRODUCT_CATALOG_DETAILS_FAIL = 'PRODUCT_CATALOG_DETAILS_FAIL'

export const REDEMPTION_CENTRE_LIST_SUCCESS = 'REDEMPTION_CENTRE_LIST_SUCCESS'
export const REDEMPTION_CENTRE_LIST_LOADING = 'REDEMPTION_CENTRE_LIST_LOADING'
export const REDEMPTION_CENTRE_LIST_FAIL = 'REDEMPTION_CENTRE_LIST_FAIL'

export const REDEMPTION_CENTRE_DETAIL_SUCCESS = 'REDEMPTION_CENTRE_DETAIL_SUCCESS'
export const REDEMPTION_CENTRE_DETAIL_LOADING = 'REDEMPTION_CENTRE_DETAIL_LOADING'
export const REDEMPTION_CENTRE_DETAIL_FAIL = 'REDEMPTION_CENTRE_DETAIL_FAIL'

export const REDEMPTION_VOUCHER_SUCCESS = 'REDEMPTION_VOUCHER_SUCCESS'
export const REDEMPTION_VOUCHER_LOADING = 'REDEMPTION_VOUCHER_LOADING'
export const REDEMPTION_VOUCHER_FAIL = 'REDEMPTION_VOUCHER_FAIL'
export const CLEAR_REDEMPTION_VOUCHER = 'CLEAR_REDEMPTION_VOUCHER'

export const VOUCHER_LIST_SUCCESS = 'VOUCHER_LIST_SUCCESS'
export const VOUCHER_LIST_LOADING = 'VOUCHER_LIST_LOADING'
export const VOUCHER_LIST_FAIL = 'VOUCHER_LIST_FAIL'

export const VOUCHER_DETAILS_SUCCESS = 'VOUCHER_DETAILS_SUCCESS'
export const VOUCHER_DETAILS_LOADING = 'VOUCHER_DETAILS_LOADING'
export const VOUCHER_DETAILS_FAIL = 'VOUCHER_DETAILS_FAIL'

export const WARRANTY_REGISTER_MODEL_NO_SUCCESS = 'WARRANTY_REGISTER_MODEL_NO_SUCCESS'
export const WARRANTY_REGISTER_MODEL_NO_LOADING = 'WARRANTY_REGISTER_MODEL_NO_LOADING'
export const WARRANTY_REGISTER_MODEL_NO_FAIL = 'WARRANTY_REGISTER_MODEL_NO_FAIL'

export const ABOUT_US_SUCCESS = 'ABOUT_US_SUCCESS'
export const ABOUT_US_LOADING = 'ABOUT_US_LOADING'
export const ABOUT_US_FAIL = 'ABOUT_US_FAIL'

export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_LOADING = 'MESSAGE_LIST_LOADING'
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'

export const MESSAGE_LIST_FILTER_SUCCESS = 'MESSAGE_LIST_FILTER_SUCCESS'
export const MESSAGE_LIST_FILTER_LOADING = 'MESSAGE_LIST_FILTER_LOADING'
export const MESSAGE_LIST_FILTER_FAIL = 'MESSAGE_LIST_FILTER_FAIL'

export const MESSAGE_DETAILS_SUCCESS = 'MESSAGE_DETAILS_SUCCESS'
export const MESSAGE_DETAILS_LOADING = 'MESSAGE_DETAILS_LOADING'
export const MESSAGE_DETAILS_FAIL = 'MESSAGE_DETAILS_FAIL'

export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS'
export const SETTINGS_LOADING = 'SETTINGS_LOADING'
export const SETTINGS_FAIL = 'SETTINGS_FAIL'